@startuml

actor main
participant ":Plataforma" as plat
participant "t:PertenenciaH" as t
participant ":EntradaB" as entrada

main -> plat : comprar(t, entradasAComprar)
plat -> t : comprar(entradasAComprar)

loop por cada entrada en entradasAComprar
t -> entrada : comprar()
entrada ->  "nuevaEntrada:EntradaB" **: <<create>>
entrada --> t : nuevaEntrada
t --> t : entradasCompradas.add(nuevaEntrada)
end

t --> plat : entradasCompradas
plat --> main : entradasCompradas

@enduml