@startuml


actor main
participant ":Plataforma" as plat
participant "t:PertenenciaH" as t
participant "Entrada" as entrada

main -> plat : comprar(t, entradasAComprar)
plat -> t : comprar(entradasAComprar)

loop por cada entrada en entradasAComprar
t -> entrada : comprar()
note right
Cada entrada devuelve
una nueva instancia
end note
entrada --> t : nuevaEntrada
t --> t : entradasCompradas.add(nuevaEntrada)

end
t --> plat : entradasCompradas

plat --> main : entradasCompradas




@enduml