@startuml
'https://plantuml.com/sequence-diagram


title se le pide el puntaje a acorazado
actor testCase
participant "a:Acorazado" as a
participant "b:BombaNeutron" as b
participant "t:TorretaIonica" as t
participant "ei:EscudoIonico" as ei

testCase -> a : puntaje()
a -> b : puntaje()
a <-- b : puntosBomba
a -> t : puntaje()
t -> b : calcularPuntosTorreta()
b --> t : puntosTorreta
a <-- t : puntosTorreta
a -> ei : puntaje()
ei -> b : puntaje()
ei <-- b: puntosBomba
ei -> t : puntaje()
ei <-- t: puntosTorreta
a <-- ei : 2*(puntosBomba+puntosTorreta)
a --> testCase: puntosAcorazado

@enduml