@startuml

class Issue {
+agregarIssue(titulo) : Issue
+agregarEpica(titulo) : Issue
+duracionEstimada(): Duracion
+promocionAEpica()
}

interface EstadoIssue {
+promocion() : EstadoIssue
}

class EstadoIssueNormal {
+promocion() : EstadoIssue
}

class EstadoIssueEpica {
+promocion() : EstadoIssue
}

Issue *-- EstadoIssue
Issue o-- "*" Issue
EstadoIssueNormal ..|> EstadoIssue
EstadoIssueEpica ..|> EstadoIssue


@enduml