@startuml
'https://plantuml.com/sequence-diagram

title LibreriaObtieneImporteDeTodosLosClientesRegistrados

actor testCase
participant ":Libreria"

testCase -> ":Libreria": importeTotalClientesRegistradosEnMes("mayo")
loop todos los clientes
":Libreria" -> ":Cliente": obtenerGastoTotal("mayo")
":Cliente" -> ":CuentaCorriente" : obtenerGastoEntreFechas("mayo", "junio")
loop para todas las compras del mes
":CuentaCorriente" -> ":Compra" : fechaCoincideEntre("mayo", "junio")
":CuentaCorriente" <-- ":Compra" : coincide
alt coincide = true
":CuentaCorriente" -> ":Compra" : obtenerPrecio()
":Compra" -> "Producto" : obtenerPrecio()
note right
    El producto
    realiza la
    logica del
    precio
end note
":Compra" <-- "Producto" : precio
":Compra" --> ":CuentaCorriente" : [totalCliente += precio]
end
end

":CuentaCorriente" --> ":Cliente": totalCliente

":Libreria" <-- ":Cliente": [total += totalCliente]
end
testCase <-- ":Libreria": total
@enduml